version: "3.8"
services:
  mariadb:
    container_name: mariadb
    networks:
      - 42-network
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_PASSWORD"]

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - "9000"
    networks:
      - 42-network
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    restart: always
    expose:
      - "9000"
    networks:
      - 42-network
    volumes:
      - adminer:/var/www/html/adminer
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: nginx
    networks:
      - 42-network
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - adminer:/var/www/html/adminer
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress

networks:
  42-network:
    driver: bridge

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/$USER/data/mariadb"
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/$USER/data/wordpress"
  adminer:
    name: "adminer"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/$USER/data/adminer"
